train:
  name: UNET_Ears_480_5_block_gen_3_block_total_segmented_augmented
  load_network: True
  phase_test: True
  load_epoch: 50
  shuffle: False
  input_nc: 3
  output_nc: 1
  n_blocks: 5
  n_networks: 1
  initial_filters: 96
  dropout_value: 0
  dont_care: False
  lr: 0.001
  decay: 0.001
  decay_epochs: 50
  batch_size: 1
  image_width: 480
  image_height: 480
  gan: False
  pool_size: 50
  lambda_gan: 1
  n_blocks_discr: 3
  dataroot: [/home/temp/schock/MGS/Eyes/Segmented_quarter_no_eyes_Augmented]
  output_path: /home/temp/schock/MGS/Suggestive_Segmentation/Outputs
  model_path: /home/temp/schock/MGS/Suggestive_Segmentation/Models
  test_path: /home/temp/schock/MGS/Subsets/Combined_Predictions
  n_epochs: 0
  steps_per_epoch: 5000
  print_freq: 1000
  save_freq: 1
  save_img_freq: 1